/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warehouse;

import dao.Category;
import dao.CategoryDAO;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author amina
 */
public class categorie extends javax.swing.JPanel {

    
     CategoryDAO cd = new CategoryDAO();
    
    /**
     * Creates new form clients
     */
    public categorie() {
        initComponents();
        updatebt.setVisible(false);
        idfield.setVisible(false);
        idlabel.setVisible(false);
        tb_load();
           
   
    }

    
     public void tb_load(){
  
  
     
          
          DefaultTableModel dt = (DefaultTableModel) TableCat.getModel();
          dt.setRowCount(0);
                  ArrayList<Category> list = cd.getAllCategories();
                  Iterator<Category> itr = list.iterator();
                  while(itr.hasNext()){
                      
                      Category categorie = itr.next();
                      dt.addRow(new Object[]{categorie.getId(),categorie.getName()});
                      
                  }
                         
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        catnom = new javax.swing.JTextField();
        addcat = new javax.swing.JButton();
        updatebt = new javax.swing.JButton();
        idlabel = new java.awt.Label();
        idfield = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCat = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        r_c = new javax.swing.JTextField();
        bt_r = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        deletecat = new javax.swing.JButton();
        edit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nom");

        catnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catnomActionPerformed(evt);
            }
        });

        addcat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/images/save-16.png"))); // NOI18N
        addcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcatActionPerformed(evt);
            }
        });

        updatebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/images/save-16.png"))); // NOI18N
        updatebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtActionPerformed(evt);
            }
        });

        idlabel.setText("ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatebt)
                    .addComponent(addcat))
                .addGap(0, 154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catnom))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(idfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catnom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(64, 64, 64)
                .addComponent(addcat)
                .addGap(18, 18, 18)
                .addComponent(updatebt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nom"
            }
        ));
        jScrollPane1.setViewportView(TableCat);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Rechercher ");

        r_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_cActionPerformed(evt);
            }
        });

        bt_r.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/images/search-3-16.png"))); // NOI18N
        bt_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(r_c, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_r)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_r)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(r_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("GERER LES CATEGORIES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(0, 256, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 146, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
        );

        deletecat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/images/delete-16.png"))); // NOI18N
        deletecat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletecatActionPerformed(evt);
            }
        });

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/images/edit-16.png"))); // NOI18N
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(edit)
                .addGap(93, 93, 93)
                .addComponent(deletecat)
                .addGap(227, 227, 227))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletecat)
                    .addComponent(edit))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deletecatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletecatActionPerformed

        int index = TableCat.getSelectedRow();
        if (index != -1) {
            TableModel model = TableCat.getModel();
            int id = (int) model.getValueAt(index,0);

            CategoryDAO caa = new CategoryDAO();
            caa.deleteCategory(id);
            refreshTable();
            JOptionPane.showMessageDialog(this, "categorie supprimée avec succès");

        }
        else {
            JOptionPane.showMessageDialog(this, "veuillez selectionner une catégorie à supprimer.");
        }

        /*
        if (selectedRow != -1) {
            int categoryId = (int) TableCat.getValueAt(selectedRow, 0);
            cd.deleteCategory(categoryId);
            JOptionPane.showMessageDialog(this, "categorie supprimée avec succès");

            refreshTable();
            //clearForm();
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        }

        */

        // TODO add your handling code here:
    }//GEN-LAST:event_deletecatActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed

        int index = TableCat.getSelectedRow();
        if (index != -1) {
            TableModel model = TableCat.getModel();

            int id = (int) model.getValueAt(index,0);
            String nom = (String) model.getValueAt(index,1);
            String idd = Integer.toString(id);
            catnom.setText(nom);

            idfield.setVisible(true);
            idlabel.setVisible(true);

            idfield.setText(idd);
            addcat.setVisible(false);
            updatebt.setVisible(true);

            // RefreshTable2();
        }
        else {
            JOptionPane.showMessageDialog(this, "veuillez selectionner une catégorie à éditer.");
        }
    }//GEN-LAST:event_editActionPerformed

    private void bt_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rActionPerformed

        String searchKeyword = r_c.getText();

        CategoryDAO dao = new CategoryDAO();
        List<Category> searchResults = dao.searchCategory(searchKeyword);
        updateTable(searchResults);
        }

        private void updateTable(List<Category> productList) {
            DefaultTableModel model = (DefaultTableModel) TableCat.getModel();
            model.setRowCount(0); //

            for (Category product : productList) {
                model.addRow(new Object[]{product.getId(), product.getName()});

            }
    }//GEN-LAST:event_bt_rActionPerformed

    private void r_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_cActionPerformed

    private void updatebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtActionPerformed

        String nom = catnom.getText();
        String idd = idfield.getText();
        int id = Integer.parseInt(idd);
        CategoryDAO dao = new CategoryDAO();
        Category c = new Category();

        c.setId(id);
        c.setName(nom);
        dao.updateCategory(c);
        refreshTable();
        JOptionPane.showMessageDialog(this, "categorie modifiée avec succès");
        addcat.setVisible(true);
        updatebt.setVisible(false);

        idfield.setVisible(false);
        idlabel.setVisible(false);
    }//GEN-LAST:event_updatebtActionPerformed

    private void addcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcatActionPerformed

        String cat_nom = catnom.getText();
        Category c = new Category();
        c.setName(cat_nom);
        CategoryDAO caa = new CategoryDAO();

        caa.addCategory(c);
        refreshTable();
        JOptionPane.showMessageDialog(null, "Catégorie ajoutée");
    }//GEN-LAST:event_addcatActionPerformed

    private void catnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catnomActionPerformed

    
  
     


private void refreshTable() {
    CategoryDAO dao = new CategoryDAO();
    List<Category> list = dao.getAllCategories(); 

    
    DefaultTableModel newTableModel = new DefaultTableModel(new Object[]{"ID", "Nom"}, 0);

   
    for (Category objet : list) {
        Object[] rowData = {objet.getId(), objet.getName()};
        newTableModel.addRow(rowData);
    }

    
    TableCat.setModel(newTableModel);
}

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableCat;
    private javax.swing.JButton addcat;
    private javax.swing.JButton bt_r;
    private javax.swing.JTextField catnom;
    private javax.swing.JButton deletecat;
    private javax.swing.JButton edit;
    private java.awt.Label idfield;
    private java.awt.Label idlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField r_c;
    private javax.swing.JButton updatebt;
    // End of variables declaration//GEN-END:variables
}
